
services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    build:
      context: jenkins-pipline
    ports:
      - '8080:8080'
    volumes:
      - /workspaces/jenkins/home/home:/var/jenkins_home
      - /workspaces/jenkins/jenkins-ansible:/var/jenkins_home/ansible/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build: 
      context: centos
    networks:
      - net
  db_host:
    container_name: db_host
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
    volumes:
      - /workspaces/jenkins/db/db:/var/lib/mysql
    networks:
      - net
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    ports:
      - '8070:80'
    volumes:
      - '/workspaces/jenkins/githome/config:/etc/gitlab'
      - '/workspaces/jenkins/githome/logs:/var/log/gitlab'
      - '/workspaces/jenkins/githome/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - net
networks:
  net:
    driver: bridge
